## WRITE YOUR DOCKER COMPOSE HERE!
version: '3'

services:
  server-service:
    build: ./server
    volumes:
      - ./server:/usr/src/app
    ports:
      - 4444:4444
    depends_on:
      - db
  db:
    image: postgres:12.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data